Henry/login page
codeboard-team/CodeBoard pull request #36
Opened 2020-05-16 04:55 UTC by Sheng-wei-Tsai

delete asset css file 
change github and google btn (login page)

2020-05-16 05:22 UTC, eudora-hsj approved these changes

2020-05-16 05:22 UTC, Luke1760 approved these changes
google登入正常
但使用github登入時，無法一次點擊就登入
已經先列在issue

2020-05-16 05:34 UTC, eudora-hsj approved these changes

2020-05-18 06:12 UTC, eudora-hsj requested changes
login error

![image](https://user-images.githubusercontent.com/52728413/82179697-839fc080-9911-11ea-913f-221396551e01.png)

2020-05-18 08:30 UTC, closed without merging